### ISSUE TITLE
Tcp connection timed out

### ISSUE THREAD

**Issue by AabidPlaysYT** [dankmeme01/globed2#101]
![Screenshot 2024-02-22 193514](https://github.com/dankmeme01/globed2/assets/160798931/f7e4d277-c868-4c80-8316-68152fa3a110)
![Screenshot 2024-02-22 193537](https://github.com/dankmeme01/globed2/assets/160798931/f59ae5d5-f31a-4e9e-8162-ee8214759f85)
it always says tcp connection timed out what do I do and im in canada not europe

**Comment by dankmeme01** [comment]
update the mod to v1.2.1 and try again

**Comment by dankmeme01** [comment]
closing since there was no response
