### ISSUE TITLE
how to run the server on Debian

### ISSUE THREAD

**Issue by Bibou1494** [dankmeme01/globed2#105]
Hello, I want to make a Globed server just for me and my friends, but i have a raspberry pi where i installed debian, and i dont know how to run the server. Can you help me please? And can i run it in root?

**Comment by dankmeme01** [comment]
get the -arm64 binaries from the latest github release, and yes you can run it with root if you want to, but it's not necessary.

the rest of the instructions can be found on the [server readme](https://github.com/dankmeme01/globed2/blob/main/server/readme.md)

**Comment by Bibou1494** [comment]
Yes but how to run it? I have the file but what's the command ti run it?

**Comment by dankmeme01** [comment]
it should work, the server is a simple executable. if it doesn't work try running `chmod +x globed-game-server-arm64` first

**Comment by Bibou1494** [comment]
Its maybe because i do chmod 777 (filename because i dont want to type the all namr)

**Comment by dankmeme01** [comment]
are you sure this is an arm64 device? if your raspberry pi runs a 32-bit OS or CPU then you can't use the arm64 binaries either, you will need to compile the server yourself.

**Comment by Bibou1494** [comment]
> are you sure this is an arm64 device? if your raspberry pi runs a 32-bit OS or CPU then you can't use the arm64 binaries either, you will need to compile the server yourself.

Its a raspberrypi 3 model b+ so idk, i installing the 64 bit version for my model and if it work. If its work, i close the issue, and if not, i close but nit completed.
