### ISSUE TITLE
new update fails to unzip

### ISSUE THREAD

**Issue by sharkdude6789** [dankmeme01/globed2#113]
on windows 11
![image](https://github.com/dankmeme01/globed2/assets/114457867/8d9d4f3a-ee7c-4253-a315-8265e36c89f1)
![image](https://github.com/dankmeme01/globed2/assets/114457867/25b23ab3-cd4c-43f8-9628-017e47076ee1)

edit: might be a geode issue but i cannot find what is at fault here

**Comment by dankmeme01** [comment]
not a globed issue, but usually can be resolved by restarting your PC.

**Comment by sharkdude6789** [comment]
tysm
