### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Helloausername** [dankmeme01/globed2#116]
crashes on android 32bit
 crashlog
[Crash 2024-03-03 09.52.18.dmp](https://github.com/dankmeme01/globed2/files/14472352/Crash.2024-03-03.09.52.18.dmp)

**Comment by muhdqausar01** [comment]
Notes: if it's black screen and it have a music on, means its not crash.. but you need to restart the game. It's makes it reset the progress itself. But if it crashes, then it save the crashlog to the folder (like you give the crashlog file) also.. how do i use voice chat on globed mobile?...

**Comment by dankmeme01** [comment]
does this crash still occur in the latest version of the mod?

**Comment by dankmeme01** [comment]
closing due to no response, if this happens again on the latest version please reopen with a new crashlog
