### ISSUE TITLE
Microphone not available for voice chat on Windows 7

### ISSUE THREAD

**Issue by EloyKraYT** [dankmeme01/globed2#118]
Here's an explanatory video:
`<iframe width="724" height="407" src="https://www.youtube.com/embed/A6caS-_IxfE" title="Explanatory video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`
And my PC's properties
![Captura](https://github.com/dankmeme01/globed2/assets/162064421/93b7c381-3446-48a8-9bb6-ab02f900ae39)
Pls help me or solve this

**Comment by EloyKraYT** [comment]
Shitty code adder...
https://youtu.be/A6caS-_IxfE

**Comment by dankmeme01** [comment]
This is a known issue, microphone does not work on windows 7. Currently there is no known fix.

**Comment by DragosDobrican** [comment]
> This is a known issue, microphone does not work on windows 7. Currently there is no known fix. 

Is there possibly a way to use the microphone that steam lets you customise with steam settings?

**Comment by dankmeme01** [comment]
globed uses the options provided by the system, the device you select in steam should not matter

**Comment by EloyKraYT** [comment]
@dankmeme01 There is an extended kernel for Windows 7, can't you take advantage of that and use it? Or in a way, translate the microphone (sort of) so it works like Windows 8?

**Comment by dankmeme01** [comment]
as of 2.206, Geode no longer runs on windows 7, so closing
