### ISSUE TITLE
Completing Challenge Failed: invalid answer to the challenge in the query parameter

### ISSUE THREAD

**Issue by FireIce421** [dankmeme01/globed2#12]
whenever i try to play on globed it spits this out, i dont know if its something in relation to my other geode mods i have on rn

List of Mods I have (excluding Globed):
BetterInfo
GradientPages
GDShare (+GMD API)
Icon Profile 2.2
Same Dual Color

**Comment by dankmeme01** [comment]
please make sure that your system clock is synced (you can do it in Windows settings), and the issue should go away.
