### ISSUE TITLE
Game crashing, seemingly because of voice chat.

### ISSUE THREAD

**Issue by TheBunnyMan123** [dankmeme01/globed2#121]
My game kept crashing, and I have disabled voice chat but I haven't been able to play long enough to see if that fixes it. I will upload crash log as comment

**Comment by TheBunnyMan123** [comment]
![Crash 2024-03-04 18.09.45.txt](https://github.com/dankmeme01/globed2/files/14490117/Crash.2024-03-04.18.09.45.txt)

This is still the dmp file, I had to rename it to txt to upload it

**Comment by TheBunnyMan123** [comment]
![Crash 2024-03-04 18.09.45.txt](https://github.com/dankmeme01/globed2/files/14490117/Crash.2024-03-04.18.09.45.txt)

This is still the dmp file, I had to rename it to txt to upload it

Edit: can confirm this is not due to voice chat

**Comment by dankmeme01** [comment]
looks like a generic libc crash, it's likely not Globed related but it could be any mod. this crash however should potentially be fixed in the next Geode update.
