### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Helloausername** [dankmeme01/globed2#124]
when leaving geode for 20+ sec geode crashes

crashlog

[Crash 2024-03-10 07.41.41.dmp](https://github.com/dankmeme01/globed2/files/14549133/Crash.2024-03-10.07.41.41.dmp)

**Comment by Helloausername** [comment]
another crashlog
[Crash 2024-03-10 08.21.27.dmp](https://github.com/dankmeme01/globed2/files/14549291/Crash.2024-03-10.08.21.27.dmp)

**Comment by Helloausername** [comment]
> just to make sure, this is on the latest version? v1.3.2?

its 1.3.2

**Comment by dankmeme01** [comment]
does this still happen on the latest version?

**Comment by dankmeme01** [comment]
closing as stale, please make a new issue if this still happens on the latest version
