### ISSUE TITLE
Crash while playing tic tac toe..

### ISSUE THREAD

**Issue by muhdqausar01** [dankmeme01/globed2#126]
Crash meanwhile playing tic tac toe in geometry hangout V2 (Most played level)
So here is the crashlog (crashed on android 32bits [Redmi S2] )
[Crash 2024-03-11 01.23.22.dmp](https://github.com/dankmeme01/globed2/files/14551230/Crash.2024-03-11.01.23.22.dmp)
Last did crash I choose X then I jump... Blocks just disappear, UI disappeared idk why. Can you fix it thanks

**Comment by dankmeme01** [comment]
does it still crash on the latest version of the mod, or was this a one time issue?

**Comment by muhdqausar01** [comment]
Uhh idk but. Yeah it's the latest version I think.. and no. It wasn't a one-time issue

**Comment by dankmeme01** [comment]
can you send a recent crashlog file, from the latest version?

**Comment by muhdqausar01** [comment]
That's the current version (idk)

**Comment by dankmeme01** [comment]
closing as stale (make a new issue if this still happens on the latest version)
