### ISSUE TITLE
Crash on startup (latest version)

### ISSUE THREAD

**Issue by MyPingO** [dankmeme01/globed2#127]
Hi, I installed Geode. Downloaded a few mods and then installed globed. It asks me to restart the game, but every time I try to start Geometry Dash, it crashes with this error ![error img](https://github.com/dankmeme01/globed2/assets/81280020/eeba5164-880d-4ed6-a8bf-a7bddd9ddb51)

Would appreciate a response on how to fix. Thanks!

**Comment by dankmeme01** [comment]
first of all, if you have any texture packs you should try to disable them. if you don't, try to verify file integrity of the game in steam.

if none of that works, you can hold shift while the game is launching to start in safe mode, after that you can open the mod list and open settings for globed, where you can disable asset preloading. this should fix the issue for now

**Comment by MyPingO** [comment]
Thank you, disabling asset preloading fixes the issue 👍
