### ISSUE TITLE
crashes before game loads

### ISSUE THREAD

**Issue by XBladeXGMD** [dankmeme01/globed2#13]
crash log

2024-02-07T18:33:08-0500
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "dankmeme.globed2" mod. Please submit this crash report to its developers (dankmeme) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.16
Loader Commit: 4f21162
Bindings Commit: c901cbb
Installed mods: 3
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll
Faulty Mod: dankmeme.globed2
Exception Code: c000001d (EXCEPTION_ILLEGAL_INSTRUCTION)
Exception Flags: 0
Exception Address: 7C0370A6 (dankmeme.globed2.dll + b70a6)
Number Parameters: 0

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + b70a6
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + acf8b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 9e539
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 91f13
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 91de5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 2c52
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 2199c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 1041b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5416b (geode::ModStateFilter::handle + 91)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 21547
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3404e (geode::DefaultEventListenerPool::handle + 78)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 341ae (geode::Event::postFromMod + 30)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + f2905 (geode::ipc::IPCFilter::handle + 69813)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e4862 (geode::ipc::IPCFilter::handle + 12306)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6161 (geode::ipc::IPCFilter::handle + 18705)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6bf3 (geode::ipc::IPCFilter::handle + 21411)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2da7f (geode::EventFilter<geode::ModInstallEvent>::setListener + 9967)
 - 01381B17
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c65a6 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 07e6d9bc
EBX: 00000002
ECX: 00000000
EDX: 00000004
EBP: 0133f34c
ESP: 0133f34c
EDI: 00000000
ESI: 07e6d998
EIP: 7c0370a6

== Installed Mods ==
o | [v1.0.1] dankmeme.globed2
x | [v1.4.0] geode.custom-keybinds
x | [v2.0.0-beta.16] geode.loader

**Comment by XBladeXGMD** [comment]
realized this was a log for 1.0.1, heres the crashlog for 1.0.2
2024-02-07T18:37:13-0500
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "dankmeme.globed2" mod. Please submit this crash report to its developers (dankmeme) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.16
Loader Commit: 4f21162
Bindings Commit: c901cbb
Installed mods: 3
Problems: 0

== Exception Information ==
Faulty Module: C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll
Faulty Mod: dankmeme.globed2
Exception Code: c000001d (EXCEPTION_ILLEGAL_INSTRUCTION)
Exception Flags: 0
Exception Address: 7C646386 (dankmeme.globed2.dll + b6386)
Number Parameters: 0

== Stack Trace ==
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + b6386
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + ac26b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 9d829
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 91213
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 910e5
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 2c52
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 2149c
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + fddb
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 5416b (geode::ModStateFilter::handle + 91)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 21047
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 3404e (geode::DefaultEventListenerPool::handle + 78)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 341ae (geode::Event::postFromMod + 30)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + f2905 (geode::ipc::IPCFilter::handle + 69813)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e4862 (geode::ipc::IPCFilter::handle + 12306)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6161 (geode::ipc::IPCFilter::handle + 18705)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + e6bf3 (geode::ipc::IPCFilter::handle + 21411)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 2da7f (geode::EventFilter<geode::ModInstallEvent>::setListener + 9967)
 - 00B81B17
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 103223 (cocos2d::CCDirector::levelForSceneInStack + 131)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c12d8
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + c65a6 (geode::utils::web::AsyncWebRequest::userAgent + 12406)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 3c267e
 - C:\Windows\System32\KERNEL32.DLL + 1fcc9 (BaseThreadInitThunk + 25)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c6e (RtlGetAppContainerNamedObjectPath + 286)
 - C:\Windows\SYSTEM32\ntdll.dll + 67c3e (RtlGetAppContainerNamedObjectPath + 238)

== Register States ==
EAX: 0b941324
EBX: 00000002
ECX: 00000000
EDX: 00000004
EBP: 00b3f63c
ESP: 00b3f63c
EDI: 00000000
ESI: 0b941300
EIP: 7c646386

== Installed Mods ==
o | [v1.0.2] dankmeme.globed2
x | [v1.4.0] geode.custom-keybinds
x | [v2.0.0-beta.16] geode.loader

**Comment by dankmeme01** [comment]
this should now be fixed in v1.0.4. if that is not the case, please reopen the issue.
