### ISSUE TITLE
[Feature Request] Add an option to stop rendering icons if they are too far

### ISSUE THREAD

**Issue by SwedishLuigi** [dankmeme01/globed2#130]
Unless it's already implemented. :)

**Comment by dankmeme01** [comment]
what is the motivation behind this? as far as i'm concerned, there isn't a noticable performance hit when rendering even hundreds of players, so i don't think this is needed

**Comment by dankmeme01** [comment]
completely stopping player rendering is not planned, however any effects and animations now won't be played if the player is too far, which is believed to have the biggest performance hit.
