### ISSUE TITLE
GD Crashes on the newest version

### ISSUE THREAD

**Issue by Olxsio** [dankmeme01/globed2#131]
When i launch GD, it crashes. But when i manually remove Globed (using the file manager), then it works.
This started happening when i upgraded to 1.3.2, it didn't happen on 1.3.1.
Btw i am using Windows 11 Pro 23H2.

**Comment by dankmeme01** [comment]
send a crashlog, and if you have any texture packs, try disabling them first

**Comment by dankmeme01** [comment]
closing due to no response, reopen if the issue still happens on the latest version

**Comment by Olxsio** [comment]
```
[ERROR] This PC is ass, session terminated
Thread NIGGGGGGGER terminated
```
Sorry for the late response, hope this helps.
