### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by Helloausername** [dankmeme01/globed2#136]
when joining a room it crashes when searching a user in a room it crashes when reloading the player list too many times it crashes

android 32bit
[Crash 2024-03-19 18.35.22.dmp](https://github.com/dankmeme01/globed2/files/14653736/Crash.2024-03-19.18.35.22.dmp)
[Crash 2024-03-19 18.39.13.dmp](https://github.com/dankmeme01/globed2/files/14653748/Crash.2024-03-19.18.39.13.dmp)
[Crash 2024-03-19 18.42.07.dmp](https://github.com/dankmeme01/globed2/files/14653766/Crash.2024-03-19.18.42.07.dmp)

**Comment by Helloausername** [comment]
mods i have are QolMod and Globed

**Comment by dankmeme01** [comment]
does this still happen on the latest version (v1.3.7)? please attach a new crashlog if it does.

**Comment by dankmeme01** [comment]
closing as stale
