### ISSUE TITLE
Globed won't let me login

### ISSUE THREAD

**Issue by hypnOX22** [dankmeme01/globed2#141]
I just downloaded globed, and it says to fix my system clock (which is 100% on time) and refresh my login. I tried the ladder, and nothing happened, and I'm not sacrificing the clock on my computer for globed.
a few fyi's: it says the clock is off by 10914 seconds which CANNOT be right, and also, this is my first time attempting to use globed, I have never touched it before.

**Comment by dankmeme01** [comment]
sync your system time. there is no other solution. you are not sacrificing anything.

**Comment by hypnOX22** [comment]
ok, but what do i even correct it to? it already is correct.

**Comment by dankmeme01** [comment]
it's not correct, you don't correct it to anything. you just press the sync button and it will sync it automatically.
