### ISSUE TITLE
crashing ever since new update

### ISSUE THREAD

**Issue by Infernogd** [dankmeme01/globed2#144]
hi ever since 1.3.7 globed won't work anymore can you please fix here is crash log
[2024-04-01_02-13-40.log](https://github.com/dankmeme01/globed2/files/14820009/2024-04-01_02-13-40.log)

**Comment by dankmeme01** [comment]
have you tried reinstalling the mod entirely? this looks like a resources issue, the game failed to find one of the textures that were added in the update.

**Comment by Infernogd** [comment]
yeah I figured out the issue it was something to do with the texture pack I had after fixing it now it works thanks
