### ISSUE TITLE
[FEATURE REQUEST] Option to hide players in practice mode

### ISSUE THREAD

**Issue by romoboss29** [dankmeme01/globed2#156]
Hello!

When I am playing a difficult level, for example bloodbath, it is very annoying seeing players in practice mode dying over and over. I know there is the hide nearby players option, but I want to see nearby players, but only the ones in normal mode. 

That's it, Thanks!
romoboss

**Comment by muhdqausar01** [comment]
enabled "hide nearby players" and "default death effect" features in globed settings so you won't get annoyed by people..

**Comment by romoboss29** [comment]
Also only normal mode players on the progress bar option would be nice

**Comment by TechStudent10** [comment]
added in #161 👍🏾

**Comment by dankmeme01** [comment]
yuh
