### ISSUE TITLE
I

### ISSUE THREAD

**Issue by ClayFuzzy** [dankmeme01/globed2#16]
![Screenshot 2024-02-08 114412](https://github.com/dankmeme01/globed2/assets/93672411/e84c8fca-8cc2-438a-b936-b36be22efb45)

**Comment by LukaTV939** [comment]
that's not how you write an issue on an open source project

**Comment by dankmeme01** [comment]
they dmed me on discord and got it resolved already i assume so closing anyway

**Comment by LukaTV939** [comment]
> they dmed me on discord and got it resolved already i assume so closing anyway

What's your discord?
