### ISSUE TITLE
crashing after installing (Linux)

### ISSUE THREAD

**Issue by andr3i1010** [dankmeme01/globed2#162]
As the title says, after installing globed and restarting the game, GD no longer works. There are no crashlogs, so I can't see why/how it crashed. I followed [this tutorial](https://www.youtube.com/watch?v=xAVfI_TGLqs) to install geode on linux.

**Comment by dankmeme01** [comment]
can you try launching with proton 7? are there crashlogs if you do that? (newer versions of proton may have a bug that causes geode crashlogs to not appear)

**Comment by andr3i1010** [comment]
I tried with proton 7, and there is a crashlog, but its empty.

**Comment by dankmeme01** [comment]
completely empty? are you sure?

try installing the [4gb patch](https://ntcore.com/4gb-patch/), it could be a memory issue. not really sure what else would cause the crashlog to be empty.

**Comment by andr3i1010** [comment]
nevermind, my deepin text editor is broken, so here is the full crashlog: https://pastebin.com/wty6z0ei

**Comment by dankmeme01** [comment]
try adding the steam launch option `--geode:globed-skip-preload` and see if that helps

**Comment by andr3i1010** [comment]
seems to work

**Comment by dankmeme01** [comment]
issue with asset preloading then, could you please send a regular log file (not crashlog) **without** the launch argument? the logs can be found in `geode/logs` in the game folder.

**Comment by andr3i1010** [comment]
this is very strange, but it suddenly got fixed.

**Comment by andr3i1010** [comment]
Nevermind, still left the disable preload param, here is the full log: https://pastebin.com/qRdDn0tY

**Comment by andr3i1010** [comment]
Nevermind, i still left the disable preload parameter, here is the full log: https://pastebin.com/qRdDn0tY

**Comment by obj-obj** [comment]
Can confirm it works, now im dying on electrodynamix with multiple people

**Comment by dankmeme01** [comment]
closing because stale, if this was not resolved in v1.4.0, please reopen or create a new issue
