### ISSUE TITLE
playing on Win7, with mic, and i cant use vc :(

### ISSUE THREAD

**Issue by DragosDobrican** [dankmeme01/globed2#163]
i got globed on my laptop, but i cant use my mic on win 7.
![Capture](https://github.com/dankmeme01/globed2/assets/165384151/e0ea6f93-f1a4-40b0-9b42-4bda0323180f)
![Capture2](https://github.com/dankmeme01/globed2/assets/165384151/d5d8a027-6bea-4838-b5b5-2d5727df2a03)

**Comment by dankmeme01** [comment]
known issue, #118
