### ISSUE TITLE
another issue so far, AND ITS ABOUT THE CLOCK.

### ISSUE THREAD

**Issue by DragosDobrican** [dankmeme01/globed2#164]
currently writing this on my laptop with the "incorrect time", even on the correct time, it keeps giving a "time is not synced" error.
![b382a11c-b700-4d6c-bf34-475e897b7571](https://github.com/dankmeme01/globed2/assets/165384151/a583a442-79c0-47ed-9389-a9baf7b7f45c)
took this picture with my tablet, so this is the best quality you will get.

**Comment by DragosDobrican** [comment]
AND, i cant change my timezone to ANY GMT timezone, and there IS no option for "24 hour" time for my laptop, BUT not even any windows version can change from "12:00 AM and PM" to "23:00 Military time".

**Comment by dankmeme01** [comment]
[synchronize your time in system settings](https://www.microcenter.com/tech_center/article/4099/how-to-enable-internet-time-synchronization-in-windows-7) (assuming this is windows 7.)

**Comment by DragosDobrican** [comment]
> [synchronize your time in system settings](https://www.microcenter.com/tech_center/article/4099/how-to-enable-internet-time-synchronization-in-windows-7) (assuming this is windows 7.)

It is Windows 7 as expected, but I'm Romanian, so I gotta use a different domain. Are there any other domains for Romanians? (For "Mineu" or "Baia Mare")

**Comment by dankmeme01** [comment]
probably

**Comment by DragosDobrican** [comment]
Thanks!
