### ISSUE TITLE
[SUGGEST] Authenticate players by their account ID, instead of username 

### ISSUE THREAD

**Issue by MegaSa1nt** [dankmeme01/globed2#167]
Hi! I'm creator of GDPS core with many new features and bugfixes
One of my features is clans
![image](https://github.com/dankmeme01/globed2/assets/49565695/6f6f647f-853a-497c-a13e-c8b737b84b7c)
Clans have tags, which you can see in-game
![image](https://github.com/dankmeme01/globed2/assets/49565695/a4763ba5-499c-4e08-ac31-9fd8ce5b8467)
The problem is it breaks Globed authentication
My guess is that Globed authenticates players by their username, can Globed authenticate players by their account ID, instead of username? No problems if no

I understand that changing way of authentication for random core is too much, but i would appreciate if you do that :)

**Comment by MegaSa1nt** [comment]
> Good idea

no clues why you commented :trollface:

**Comment by dankmeme01** [comment]
how exactly does it break globed authentication? is there any specific error message you could provide?

**Comment by dankmeme01** [comment]
implemented in https://github.com/dankmeme01/globed2/commit/5f21c2b35ca4e27daa7fdd37d01d321a6a0a3297, will be added in the next update of the server

if there will still be any other issues, please reopen

**Comment by MegaSa1nt** [comment]
Thank you very much ❤️
