### ISSUE TITLE
Failed loading

### ISSUE THREAD

**Issue by Zaedlol** [dankmeme01/globed2#176]
Its not working
![Screenshot_20240615-183516](https://github.com/dankmeme01/globed2/assets/172920766/0db69f41-0382-4200-bc67-fc764b295f73)
![Screenshot_20240615-183516](https://github.com/dankmeme01/globed2/assets/172920766/8bca30ff-cdaf-45b3-bce1-8ea8fc8d531c)

SEE

**Comment by dankmeme01** [comment]
mod is not out for 2.206, wait for an update
