### ISSUE TITLE
failed to fetch servers (error code: 502)

### ISSUE THREAD

**Issue by randomaccount20** [dankmeme01/globed2#188]
im a mobile player (also in pc).
so the issue is that everytime i try to use globed on mobile it just sends me an error:

**"Failed to fetch servers (code 502)
 (error code: 502)"**

and when i try pressing the login button it sends me another error:

**"Creating challenge failed: error code: 502"**

is this intentional? i really wanna play with my mobile friend online using globed but this error isn't letting me

**Comment by dankmeme01** [comment]
Globed only supports the latest version of Geometry Dash, 2.206. This error means you are using an old version of the game.
