### ISSUE TITLE
Europe server missing

### ISSUE THREAD

**Issue by HelloWorld77246** [dankmeme01/globed2#190]
The Europe server is missing. Is there a workaround?

**Comment by HelloWorld77246** [comment]
<img width="1023" alt="Screenshot 2024-06-25 at 12 11 30 PM" src="https://github.com/dankmeme01/globed2/assets/113399601/1cf7d056-f3bc-4919-a1f2-e2fccdad0824">

**Comment by dankmeme01** [comment]
fixed in v1.4.2
