### ISSUE TITLE
Geometry Dash crash when completing created levels

### ISSUE THREAD

**Issue by HelloWorld77246** [dankmeme01/globed2#192]
https://github.com/dankmeme01/globed2/assets/113399601/faa21518-9f81-45b8-b16d-aafeadf0f457

There's a weird bug that causes Geometry Dash to crash whenever I complete a level I created.
[2024-06-25_14-18-35.log](https://github.com/user-attachments/files/15977037/2024-06-25_14-18-35.log)

**Comment by dankmeme01** [comment]
fixed in v1.4.2
