### ISSUE TITLE
Bug needed of fixing

### ISSUE THREAD

**Issue by RealRealPurple** [dankmeme01/globed2#199]
### **Bug with the mod installed**

So, at least on my device, if you install globed, whenever you **try** to open the editor with the mod installed, the game crashes. This may only be a bug with some devices, but it would be nice if the bug was fixed. 
**Thank you for your time.**
![image](https://github.com/dankmeme01/globed2/assets/134749808/67467271-7888-4b88-97f2-00a25c13a839)
![image](https://github.com/dankmeme01/globed2/assets/134749808/d5c16bd3-54c5-4ad4-9de5-88f52328cfe5)

**Comment by dankmeme01** [comment]
sned crashlog please

**Comment by RealRealPurple** [comment]
I just tried to get the error message but it does not seem to crash my game anymore. this can now be closed.
