### ISSUE TITLE
The game crashes (it didn't even start completely)

### ISSUE THREAD

**Issue by Alyoshadash** [dankmeme01/globed2#2]
What should I do if my GD just crashes? I even deleted all mods (except custom keybinding) well, it still doesn't help. How can I fix this? (I can send crashlogs of each error)

**Comment by Nemyam** [comment]
You can try download last version from actions, for me its worked.

**Comment by Alyoshadash** [comment]
I had the latest version of custom keybinding. Or do you mean something else?

**Comment by Nemyam** [comment]
[I mean here](https://github.com/dankmeme01/globed2/actions/runs/7818781647/artifacts/1227739763)
