### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by jamescraft10** [dankmeme01/globed2#207]
2024-07-19T23:28:19-0400
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.2.0
Loader Commit: 65ed0d4
Bindings Commit: 103fbd9
Installed mods: 16
Problems: 0

== Exception Information ==
Faulty Module: Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00006FFFFBD0FB37 (Geode.dll + 3fb37 (GeodeNodeMetadata::getFieldContainer + 407 | Z:\home\runner\work\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:70))
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 3fb37 (GeodeNodeMetadata::getFieldContainer + 407 | Z:\home\runner\work\geode\geode\loader\src\hooks\GeodeNodeMetadata.cpp:70)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 8162c
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + 82f23
 - 0000000001240C72 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 12138e
 - 0000000001245472 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 68fb6
 - 0000000001245472 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 2f337
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 2ec23
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 35902
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 3308c
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 72b0b (geode::DefaultEventListenerPool::handle + 491 | Z:\home\runner\work\geode\geode\loader\src\loader\Event.cpp:52)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 370c1
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 35d68
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 85ac
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 72b0b (geode::DefaultEventListenerPool::handle + 491 | Z:\home\runner\work\geode\geode\loader\src\loader\Event.cpp:52)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\geode.custom-keybinds\geode.custom-keybinds.dll + 62eb9
 - 000000000123A872 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\geode\unzipped\thesillydoggo.qolmod\thesillydoggo.qolmod.dll + acdf1
 - 000000000123A872 (Hook handler)
 - 000000000123A872 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 75edd
 - 0000000001246C84 (Hook handler)
 - 0000000001246C84 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 7604e
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + d6702
 - C:\windows\system32\user32.dll + 55711
 - C:\windows\system32\user32.dll + 5ac13
 - C:\windows\system32\user32.dll + 5aa0e
 - C:\windows\system32\user32.dll + 1b654
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 23a41a (gdMainHook + 554 | Z:\home\runner\work\geode\geode\loader\src\platform\windows\main.cpp:167)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\windows\system32\kernel32.dll + 1473d
 - C:\windows\system32\ntdll.dll + f3ff

== Register States ==
RAX: 0000000000000003
RBX: 0000000000000000
RCX: 00000100000001b3
RDX: 000000000011e23c
RBP: 0000000000000000
RSP: 000000000011ffb0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00006ffffff4f3ff
R8:  e751d6f45b36c564
R9:  e751d6f45b36c564
R10: 0000000000000003
R11: 000000000011e270
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v4.2.4] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
  | [v1.5.1] dankmeme.globed2
x | [v1.7.1] geode.custom-keybinds
x | [v3.2.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.2.1] hjfod.gmd-api
x | [v2.1.0] iandyhd3.wsliveeditor
  | [v1.2.0] itzkiba.grandpa_demon
x | [v1.3.7-beta.1] m336.levelinfo
x | [v1.1.2] mat.run-info
  | [v1.1.20] syzzi.click_between_frames
x | [v2.3.1] thesillydoggo.gradientpages
x | [v1.4.8] thesillydoggo.qolmod

**Comment by dankmeme01** [comment]
Qolmod crash, not Globed. Report to its developer
