### ISSUE TITLE
timeout reached

### ISSUE THREAD

**Issue by downloader999** [dankmeme01/globed2#208]
i made my own server and decided to open it but i got a error that the timeout was reached so can anyone tell me the timeout from a default server**??**

**Comment by dankmeme01** [comment]
that means you did not setup the server correctly, and the game was not able to connect.

**Comment by downloader999** [comment]
i followed the page

**Comment by dankmeme01** [comment]
if it's a standalone server use the Direct Connection option in-game, not Add Server

**Comment by downloader999** [comment]
its a central server and everything in the notepad seems fine

**Comment by downloader999** [comment]
okay i did it bye
