### ISSUE TITLE
crash (linux)

### ISSUE THREAD

**Issue by jamescraft10** [dankmeme01/globed2#209]
2024-07-22T16:11:13-0400
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.3.0
Loader Commit: ecc83ca
Bindings Commit: fd133d1
Installed mods: 16
Problems: 0

== Exception Information ==
Faulty Module: Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe
Faulty Mod: <Unknown>
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00000001404875EF (GeometryDash.exe + 4875ef)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 4875ef
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 487584
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 2cd298
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + ddffe
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 597cf
 - 0000000001010872 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 3c0a5 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | Z:\home\runner\work\geode\geode\build\bindings\bindings\Geode\modify\CCMenuItem.hpp:35)
 - 0000000001010872 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 58798
 - 0000000001010C72 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 3c76f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | Z:\home\runner\work\geode\geode\build\bindings\bindings\Geode\modify\CCMenu.hpp:105)
 - 0000000001010C72 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + b0c3c
 - 00000000019B6072 (Hook handler)
 - 00000000019B6072 (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 6b131
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 76159
 - 00000000019C807B (Hook handler)
 - 00000000019C807B (Hook handler)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 76186
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + d686b
 - C:\windows\system32\user32.dll + 55711
 - C:\windows\system32\user32.dll + 5ac13
 - C:\windows\system32\user32.dll + 5aa0e
 - C:\windows\system32\user32.dll + 1b654
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + d4198
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\libcocos2d.dll + 72ca6
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\Geode.dll + 23c28a (gdMainHook + 554 | Z:\home\runner\work\geode\geode\loader\src\platform\windows\main.cpp:167)
 - Z:\home\jamescraft\.steam\debian-installation\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\windows\system32\kernel32.dll + 1473d
 - C:\windows\system32\ntdll.dll + f3ff

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 4059000000000000
RDX: 000000000011e660
RBP: 0000000000000000
RSP: 000000000011ffb0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00006ffffff4f3ff
R8:  0000000000000032
R9:  00006ffffdc0129f
R10: 00006ffffdbf0000
R11: 0000000000b01800
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v4.2.4] cvolton.betterinfo
x | [v1.0.0] cvolton.level-id-api
x | [v1.2.0-beta.2] cvolton.misc_bugfixes
  | [v1.5.1] dankmeme.globed2
x | [v1.7.1] geode.custom-keybinds
x | [v3.3.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.2.1] hjfod.gmd-api
x | [v2.1.0] iandyhd3.wsliveeditor
  | [v1.2.0] itzkiba.grandpa_demon
x | [v1.3.7-beta.1] m336.levelinfo
x | [v1.1.2] mat.run-info
  | [v1.1.20] syzzi.click_between_frames
x | [v2.3.1] thesillydoggo.gradientpages
x | [v1.4.9] thesillydoggo.qolmod

**Comment by jamescraft10** [comment]
it happend when i save and exit

**Comment by dankmeme01** [comment]
this sounds like a vanilla bug, i've seen someone having the same crash without any mods enabled. seems to be related to text objects in the editor.

not a globed issue so closing
