### ISSUE TITLE
globed keeps crashing

### ISSUE THREAD

**Issue by Ev212** [dankmeme01/globed2#214]
whenever i get onto globed its fine but when i try to click on the 2nd level it crashes (not the 1st)

**Comment by dankmeme01** [comment]
please upload crashlog

**Comment by Ev212** [comment]
[2024-07-28_13-15-31.txt](https://github.com/user-attachments/files/16405307/2024-07-28_13-15-31.txt)
here

**Comment by dankmeme01** [comment]
looks like an issue with the Level Info mod, not globed
