### ISSUE TITLE
game crashes while executing code from globed

### ISSUE THREAD

**Issue by bsaweee** [dankmeme01/globed2#22]
![Screenshot 2024-02-08 090202](https://github.com/dankmeme01/globed2/assets/155666932/62afa7e0-aa5c-479f-b0d9-428eba8f6843)
alright so i have the image now so you probably gotta look at what is wrong with the mod and just let me know when you do know the issue

**Comment by dankmeme01** [comment]
i'm assuming this is an old version? have you tried this on the latest one (v1.0.4)?

**Comment by bsaweee** [comment]
oh it works now on the new version i just couldnt update it because the game kept crashing because i have a old cpu so thanks alot for telling me this and thanks for making a epic mod for us
