### ISSUE TITLE
Globed crashes all the time when HDR/Auto-HDR is Enabled.

### ISSUE THREAD

**Issue by IgLocoXD** [dankmeme01/globed2#27]
(btw niko profile picture absolutely fucking based)

The game will never load when HDR/Auto-HDR is enabled, for some reason, Globed refuses to work.

![image](https://github.com/dankmeme01/globed2/assets/82992516/c9a7f450-77f2-425b-99c5-fd0cfb15ecd0)

**Comment by dankmeme01** [comment]
interesting, i have seen this issue before but i couldn't correlate it to HDR. just to clarify, if you disable Death effects in globed settings, and set the steam launch option `--geode:globed-skip-death-effects=true`, does the crash stop happening?

**Comment by IgLocoXD** [comment]
Well, interestingly, it opens, so i think is that

**Comment by dankmeme01** [comment]
could you try again on the latest version (v1.0.5)? remove the launch argument in Steam (and make sure that "Preload assets" is enabled in settings), and try starting the game.

the way death effects (and icons) are loaded has been changed so i believe the issue may be resolved now, but i cannot reproduce it myself so i want to make sure.

**Comment by dankmeme01** [comment]
closing as stale
