### ISSUE TITLE
network issue

### ISSUE THREAD

**Issue by SergeyMC9730** [dankmeme01/globed2#29]
globed tries to create udp connection. nothing happens but a timeout error.
![изображение](https://github.com/dankmeme01/globed2/assets/57207009/ee34bfac-d45c-4f61-b639-373a9b272546)

```
14:55:12 ERROR [Network (in) Thread] [Globed]: Failed to connect to the server. No response was received after 5 seconds.
```

proxy connection isn't used to create server connection.

network setup:
![изображение](https://github.com/dankmeme01/globed2/assets/57207009/5bba145d-dfbd-45b7-add0-1683b318d881)

**Comment by SergeyMC9730** [comment]
this bug still persists in v1.1.0

**Comment by s4mat** [comment]
![изображение](https://github.com/dankmeme01/globed2/assets/80270161/b3c948b4-a9d6-4ef5-a99d-8cafbee88ece)
what
