### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Nemyam** [dankmeme01/globed2#3]
[Win error 10051]: A socket operation was attempted to an unreachable network. But I have [2024-02-07 18:16:18.799] [INFO] - (bypassed) successfully generated an authkey for (my nick is secret)
in my server console. And why?

**Comment by Nemyam** [comment]
maybe this problem in my windows, even 127.0.0.1:41000 is dont work

**Comment by dankmeme01** [comment]
sounds like an issue with your internet connection, are you sure there are no firewalls or any other things that could block globed?

**Comment by Nemyam** [comment]
hmm strange, main server is working, but my servers is no

**Comment by dankmeme01** [comment]
i believe this was an issue with the default server configuration, the server configuration template had the address set as `127.0.0.0` whereas it should've been `127.0.0.1`. either way the template has been fixed and if you still have the issue, change the address in your configuration file manually.
