### ISSUE TITLE
Mobile Port

### ISSUE THREAD

**Issue by Navigator000** [dankmeme01/globed2#31]
While it is great that this mod is even a thing, the mod will be amazing if ported to mobile, as a majority of the playerbase doesn't use PC/Steam and people like us are still not able to use this. I hope you are able to get a port soon, as I would love to see this.

**Comment by Nemyam** [comment]
If this mod will released on android, it will be very very cool

**Comment by SmallLSplash** [comment]
Please add one please I wanna play gd multiplayer

**Comment by mishpro-programm** [comment]
+

**Comment by BeepyDev** [comment]
The devs are able to close dupes but not write a simple reply, that's crazy tbh

**Comment by romoboss29** [comment]
I would also appreciate macOS support

**Comment by dankmeme01** [comment]
added in v1.3.0 and already out on the geode index
