### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Nemyam** [dankmeme01/globed2#34]
How idea add teleport to player (if he have enabled Teleport enabled, other player i mean) and view other player (also View Enabled)

**Comment by FurnyGo** [comment]
only if it will be available after completing the level, but it may cause bugs with triggers

**Comment by Nemyam** [comment]
yeah

**Comment by dankmeme01** [comment]
was added as an admin ability a while ago, will not be added to regular players since it is easily abusable
