### ISSUE TITLE
Mobile Globed

### ISSUE THREAD

**Issue by SmallLSplash** [dankmeme01/globed2#38]
Please do this as not a lot of people have PCs these days and hardly any mobile players get the chance to experience gd multiplayer plsssss

**Comment by Geming400** [comment]
It will maybe come one day. It's just low priority

**Comment by dankmeme01** [comment]
duplicate issue

**Comment by SmallLSplash** [comment]
> duplicate issue

Please just try to fix it I really wanna play gd multiplayer😭

**Comment by muhdqausar01** [comment]
> > duplicate issue
> 
> Please just try to fix it I really wanna play gd multiplayer😭

Yeah me too😭😭😭
