### ISSUE TITLE
Beating Gauntlet Levels prevents you from advancing.

### ISSUE THREAD

**Issue by mariokirby1703** [dankmeme01/globed2#4]
I just completed Crush (1st Level of the Castle Gauntlet) with my friends.
I accessed the level through the Gauntlets and after I beat it it showed 100% on both the Gauntlet and non-Gauntlet Version of the Level. This is an issue too cause you only get the stats once...
After I backed out of the Level Screen on Crush on the Gauntlet Version, the Path to the next level didnt appear and the number of completed Levels in the Gauntlet is still at 0/5. 
I left the Globed Server and restarted my Game but it still shows 100% on the Gauntlet and no path to the next Level...

![20240207192024_1](https://github.com/dankmeme01/globed2/assets/60894103/9cbe8212-5007-4d2b-ac66-ee2a774fbdea)
![20240207192028_1](https://github.com/dankmeme01/globed2/assets/60894103/a1a910f0-03bb-4f97-a21b-1b33f6a6a7e2)
![20240207192131_1](https://github.com/dankmeme01/globed2/assets/60894103/cb89126f-1e68-4f2f-9bd9-3982fe833d33)

**Comment by mariokirby1703** [comment]
Edit: it only happens to levels from the Castle Gauntlet...

**Comment by dankmeme01** [comment]
issue fixed in next release
