### ISSUE TITLE
Global room doesn't load.

### ISSUE THREAD

**Issue by TBRHSonGitHub** [dankmeme01/globed2#43]
![image](https://github.com/dankmeme01/globed2/assets/147876563/f4f053a1-4052-4a41-81f2-6d9f5ec3b326)
Stuck on a loading loop. Can't find a solution, nor finding anything related to this loading loop before.
The only reason i installed this is because it was from an SDSlayer video and i can't join anyone on this device.
I downloaded all of the other mods required for this one.

**Comment by dankmeme01** [comment]
known bug, should be fixed by the switch to a different networking protocol in a future update

**Comment by dankmeme01** [comment]
should be fixed in v1.1.0
