### ISSUE TITLE
"invalid answer to the challenge in the query parameter"

### ISSUE THREAD

**Issue by Bituvo** [dankmeme01/globed2#51]
My brother was playing Geometry Dash (installed from my Steam account) and he is logged in to his account ("MachineBlade"). He cannot use the mod, because when he presses the "Log In" button, he gets this error. Is there anything we can do?

He's already tried reinstalling Geode and Globed.

**Comment by dankmeme01** [comment]
known bug with no real solution from my side.

to fix, open your system settings and synchronize your time.

**Comment by theParkourRat** [comment]
> known bug with no real solution from my side.
> 
> to fix, open your system settings and synchronize your time.

I have the same issue and the time is synchronized. The error still persists, what else can i do?
