### ISSUE TITLE
Unknown crash after some hours on server

### ISSUE THREAD

**Issue by FurnyGo** [dankmeme01/globed2#52]
![image](https://github.com/dankmeme01/globed2/assets/68079109/b39975aa-dc84-4f52-bd25-c7ee3b45e6a9)
crashlog [2024-02-12_19-26-22.log](https://github.com/dankmeme01/globed2/files/14240150/2024-02-12_19-26-22.log)
logs [Geode 2024-02-12 16.50.08.log](https://github.com/dankmeme01/globed2/files/14240153/Geode.2024-02-12.16.50.08.log)

**Comment by dankmeme01** [comment]
likely audio related race condition and should've been fixed in v1.1.2
