### ISSUE TITLE
Game crashing :/

### ISSUE THREAD

**Issue by CreeperSmurf02** [dankmeme01/globed2#54]
My games crashes everytime I open it with globed. I only have globed, custom keybinds and the node ids mods turned on. Here is the crashlog: 
[2024-02-12_14-09-04.log](https://github.com/dankmeme01/globed2/files/14248514/2024-02-12_14-09-04.log)

**Comment by dankmeme01** [comment]
just curious, does this still happen on the latest version of geode and globed? this is a really strange crash and the crashlog doesn't help me much in resolving the issue

**Comment by dankmeme01** [comment]
closing due to no response, if this happens again on the latest version please attach a crashlog
