### ISSUE TITLE
Crash whenever I press V to talk.

### ISSUE THREAD

**Issue by LNLenost** [dankmeme01/globed2#57]
pls help!!

**Comment by dankmeme01** [comment]
duplicate of #56

**Comment by LNLenost** [comment]
You closed the thread but didn't helpwd me...

**Comment by LNLenost** [comment]
these are the logs btw
[Geode 2024-02-13 11.52.02.log](https://github.com/dankmeme01/globed2/files/14269872/Geode.2024-02-13.11.52.02.log)
