### ISSUE TITLE
Crash when click on "Position" on Overlay settings

### ISSUE THREAD

**Issue by Miifuu** [dankmeme01/globed2#6]
When I click on "Position" button on the Overlay settings, my game crash...
Crash log: [2024-02-07_20-14-55.log](https://github.com/dankmeme01/globed2/files/14200543/2024-02-07_20-14-55.log)

**Comment by dankmeme01** [comment]
fixed in next release (https://github.com/dankmeme01/globed2/commit/ad012619aeceb0c1974e76e1e2309fea85b08c5a)
