### ISSUE TITLE
All Icons sharing the same colour set (mine)

### ISSUE THREAD

**Issue by KontrollFreek** [dankmeme01/globed2#61]
no clue, happened in 1.0.5 for some reason and has not gone away
![20240213195341_1](https://github.com/dankmeme01/globed2/assets/72424960/458e5a3f-3812-40a0-8874-36ff48472a35)

**Comment by dankmeme01** [comment]
do you have the "Same dual color" mod installed? this is a conflict with that mod

**Comment by KontrollFreek** [comment]
ohh that's why that happens, thanks
