### ISSUE TITLE
win error 10057

### ISSUE THREAD

**Issue by Rogox14** [dankmeme01/globed2#63]
![imagen_2024-02-13_232115408](https://github.com/dankmeme01/globed2/assets/77737200/ed5073fd-051a-48f0-9f4d-71712c11aec9)

what is going on?

**Comment by dankmeme01** [comment]
is this still happening? the servers were going through a restart at the time of you making this issue.

**Comment by Rogox14** [comment]
not happening anymore, it kinda fixed itself after some time so maybe it was the server restarting as you say
