### ISSUE TITLE
Error 521 when looking for servers.

### ISSUE THREAD

**Issue by Sushi8756** [dankmeme01/globed2#64]
Got disconnected from Globed a few times then now I can even look for servers, this shows up.

![image](https://github.com/dankmeme01/globed2/assets/90991195/d3a43f8f-fb54-4fa1-ba32-6ef45f60e39d)

**Comment by dankmeme01** [comment]
is this still happening? the servers were going through a restart at the time of you making this issue.

**Comment by Sushi8756** [comment]
> is this still happening? the servers were going through a restart at the time of you making this issue.

oh 💀 I guess it was because of that.
