### ISSUE TITLE
Globed Error

### ISSUE THREAD

**Issue by JordanTRS** [dankmeme01/globed2#65]
"Creating challenge failed: You had only one shot" wtf does this mean

**Comment by dankmeme01** [comment]
intended behavior, user is banned from the server

**Comment by JordanTRS** [comment]
well, I never got a ban reason, and I never broke any rules. And assuming this is due to me "being a pedophile" then I'd like to request you reconsider, as while I have made a lot of stupid mistakes, I have never been a pedophile, nor have I ever groomed anyone.

**Comment by dankmeme01** [comment]
this is something i am not willing to discuss in a github issue, nor in general. there are no plans to revert the ban.

**Comment by JordanTRS** [comment]
> this is something i am not willing to discuss in a github issue, nor in general. there are no plans to revert the ban.

guess that's code for "I don't want to admit I'm wrong so I'm gonna make up an excuse to keep you banned" man if you aren't even gonna consider letting people defend themselves then you're not suited to run a big project like this, I'm be perfectly honest. good for you tho 👍

**Comment by erreing** [comment]
why was he banned tho
