### ISSUE TITLE
globed error completing challenge failed

### ISSUE THREAD

**Issue by thewokgamur** [dankmeme01/globed2#68]
im in authentication when login globed error completing challenge failed: challenge does not exist for this id addres appear

**Comment by 72888hshu** [comment]
got the same problem (kinda):
![image](https://github.com/dankmeme01/globed2/assets/48046222/447a7a21-0fc7-4370-ac09-57d4dd6edaeb)

**Comment by 72888hshu** [comment]
nevermmind mine just need to waitt for server to back up online and update the mod
