### ISSUE TITLE
Failed to connect to the server no response was received after 5 seconds

### ISSUE THREAD

**Issue by Regulargdplay12** [dankmeme01/globed2#69]
ive been trying to play globed but everytime i get an error saying that no response was received when trying to connect the server how do i fix how do i fix how do i fix how do i fix how do i fix how do i fix how do i fix how do i fix 
![image](https://github.com/dankmeme01/globed2/assets/160042856/0593a55c-7070-422d-a7cd-94561641d334)

**Comment by EMREOYUN** [comment]
Something blocking your connection. Try with different connection.

**Comment by dankmeme01** [comment]
closing as stale (make a new issue if this is still happening)

**Comment by platonkornilov11-afk** [comment]
what i need to do tj fix this problem 

<img width="1219" height="497" alt="Image" src="https://github.com/user-attachments/assets/25c67973-d393-4a48-8ad2-1ca9c1052b16" />
