### ISSUE TITLE
Globed causing Lag Spikes in levels

### ISSUE THREAD

**Issue by pizzellefromsugaryspire** [dankmeme01/globed2#78]
Whenever i play a level with players on it, it causes it to randomly freeze, and then in the end making me die.
Note that my PC is totally capable for online games, as i've played games that use more than globed and GD.

**Comment by dankmeme01** [comment]
can you try the latest version (v1.1.1) and tell if the issue still occurs? some lagspike issues were fixed in that specific update

**Comment by pizzellefromsugaryspire** [comment]
> can you try the latest version (v1.1.1) and tell if the issue still occurs? some lagspike issues were fixed in that specific update

ok, on it

**Comment by pizzellefromsugaryspire** [comment]
> can you try the latest version (v1.1.1) and tell if the issue still occurs? some lagspike issues were fixed in that specific update

thanks! it's fixed now, i tried it on a couple fast levels, and for now there hasn't been any lag spikes!
