### ISSUE TITLE
[Voice Chat] Voice chat not working

### ISSUE THREAD

**Issue by MessiInter** [dankmeme01/globed2#84]
When I press V to voice chat it give me this error:
![image](https://github.com/dankmeme01/globed2/assets/136736943/0dccb2b4-a941-4162-b475-7b9d15f0d2f8)
Even i selected the right microphone and tested it in Globed settings.
![image](https://github.com/dankmeme01/globed2/assets/136736943/012852d1-f37e-4002-b2e5-fd90ffef99ba)
Microphone Array (IDT High Definition Audio Codec) is my main microphone. Other are microphone but in the 3.5 audio jack

**Comment by EMREOYUN** [comment]
Are you sure that device is enabled, working properly, can be initialized instantly, and not using by any other device?

**Comment by MessiInter** [comment]
My microphone is ready to initialized and I can test the microphone in Globed > Settings > Audio Device [Voice Chat] but can't use it when play a level

**Comment by dankmeme01** [comment]
this is a known issue on windows 7. currently no known fix

**Comment by brianthanhbinh** [comment]
for some reason the mic bar go crazy although it's not loud outside
