### ISSUE TITLE
[Server] Firewall Rules

### ISSUE THREAD

**Issue by EMREOYUN** [dankmeme01/globed2#85]
I'm using a firewall to filter/block unnecessary connections. However, even though I allowed the ports and the program itself, it keeps disconnecting due lack of response from server. After connecting, it cannot load anything. Which protocols and ports used outside of configured ports?

**Comment by dankmeme01** [comment]
server-side the used protocols are TCP and UDP on the same port (41001 by default but can be changed).

client-side there's no specific port number (they are random), but TCP and UDP connections should be allowed to be able to connect.

**Comment by EMREOYUN** [comment]
> server-side the used protocols are TCP and UDP on the same port (41001 by default but can be changed).
> 
> client-side there's no specific port number (they are random), but TCP and UDP connections should be allowed to be able to connect.

Currently, only allowing 41001 results no ping information and no packet sending so it disconnects. Disabling the firewall resolves the problem but I have to keep the firewall.

**Comment by dankmeme01** [comment]
when you try to connect, does the server name become green for a few seconds? if so, this means a TCP connection succeeded but not the UDP connection.

if nothing happens at all, and you get a popup saying that you get disconnected, then you are unable to send neither TCP nor UDP packets.

**Comment by EMREOYUN** [comment]
Yes, the server name becomes green. Even though I allow the ports in both TCP and UDP, it still disconnects.

And yes, firewalls isn't your thing to fix but since you wrote the connection handlers, I wanted to know is there anything specific(like other ports, a range of ports that acts like handlers, other technologies such as ICMP used on pings, etc) to know so I can adjust the firewall with it.

**Comment by dankmeme01** [comment]
pings use UDP packets as well, not ICMP. the only two protocols used are UDP and TCP, on the same exact port server-side (41001).

if this doesn't help then i'm not sure how much more information i can provide

**Comment by EMREOYUN** [comment]
> pings use UDP packets as well, not ICMP. the only two protocols used are UDP and TCP, on the same exact port server-side (41001).
> 
> if this doesn't help then i'm not sure how much more information i can provide

Yup, that's what I looking for. Finally set the server up and running.
