### ISSUE TITLE
Geometry Dash Crashed. It appears that the crash occurred while executing code from the "dankmeme.globed2" mod.

### ISSUE THREAD

**Issue by 1SonNguyen** [dankmeme01/globed2#87]
---------------------------
Geometry Dash Crashed
---------------------------
2024-02-18T10:47:19+0700
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "dankmeme.globed2" mod. Please submit this crash report to its developers (dankmeme) for assistance.

== Geode Information ==
Loader Version: v2.0.0-beta.20
Loader Commit: 453fac9
Bindings Commit: 60e063e
Installed mods: 8
Problems: 0

== Exception Information ==
Faulty Module: C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll
Faulty Mod: dankmeme.globed2
Exception Code: c00000fd (EXCEPTION_STACK_OVERFLOW)
Exception Flags: 0
Exception Address: 6C74A627 (dankmeme.globed2.dll + da627)
Number Parameters: 2

== Stack Trace ==
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + da627
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\dankmeme.globed2\dankmeme.globed2.dll + 23eec
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\libcocos2d.dll + 107031 (cocos2d::CCTimer::update + 97)
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\libcocos2d.dll + 106ec4 (cocos2d::CCScheduler::update + 276)
 - 03212D76
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 46096
 - 03212B97
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\maxnu.gd_mega_overlay\maxnu.gd_mega_overlay.dll + 36346
 - 03212B97
 - 03822DC9
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\geode\unzipped\geode.devtools\geode.devtools.dll + 64db
 - 03822BEB
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\GeometryDash.exe + 3c12d8
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\Geode.dll + 16f4d4 (crashlog::setupPlatformHandlerPost + 3956)
 - C:\Users\quang\OneDrive\Tài liệu\Geometry.Dash.v2.204a\GeometryDash.exe + 3c267e
 - C:\WINDOWS\System32\KERNEL32.DLL + 15d49 (BaseThreadInitThunk + 25)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6baeb (RtlInitializeExceptionChain + 107)
 - C:\WINDOWS\SYSTEM32\ntdll.dll + 6ba71 (RtlGetAppContainerNamedObjectPath + 561)

== Register States ==
EAX: 00cc2000
EBX: 20875018
ECX: 00b16acc
EDX: 00000000
EBP: 00dbf4e0
ESP: 00dbf4c0
EDI: 1960a4cc
ESI: 000aa27b
EIP: 6c74a627

== Installed Mods ==
x | [v1.1.2] dankmeme.globed2
x | [v1.5.2] geode.custom-keybinds
x | [v1.5.0] geode.devtools
x | [v2.0.0-beta.20] geode.loader
x | [v1.6.1] geode.node-ids
x | [v1.5.0] geode.texture-loader
x | [v1.1.1] itzkiba.formatted_platformer_time
x | [v2.5.3] maxnu.gd_mega_overlay

---------------------------
OK   
---------------------------

**Comment by MessiInter** [comment]
Try reinstall Globed mod

**Comment by dankmeme01** [comment]
i believe it's an audio related issue, potentially fixed in next update (https://github.com/dankmeme01/globed2/commit/cff322b8d625de9139791f20c464eee92cf5c68f)
