### ISSUE TITLE
game crashes when it tries to execute code from this mod

### ISSUE THREAD

**Issue by bsaweee** [dankmeme01/globed2#9]
the game is regular with loading other mods but then it tries to load this mod also then it just crashes as soon as it executes the code, is there anyway to fix it or do i need to uninstall the mod?

**Comment by dankmeme01** [comment]
there's no crashlog so it's impossible to tell what's the issue, but if v1.0.2 didn't fix the crash, please reopen the issue and attach a crashlog.

and yes, you will need to manually uninstall the mod in order to update it (because it crashes on load)

**Comment by bsaweee** [comment]
oh sorry i was asleep so heres the error code for you and tell me if i did something wrong  with the download.
![Screenshot 2024-02-08 090202](https://github.com/dankmeme01/globed2/assets/155666932/46b89ac2-913d-4d4f-a372-173ab31105f5)
