### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by Hellogithubnew** [dankmeme01/globed2#90]
PLEASE MAKE GLOBED AVAILABLE ON ANDROID I AM GOING ABSOLUTELY INSANE SINCE I FOUND OUT THAT GLOBED ISNT AVAILABLE ON ANDROID PLEASE

**Comment by Hellogithubnew** [comment]
PLEASEEEEEE

**Comment by dankmeme01** [comment]
duplicate #31
