### ISSUE TITLE
entering a ball portal while mini doesnt switch icon to ball

### ISSUE THREAD

**Issue by ImXyper** [dankmeme01/globed2#93]
i am in the ball gamemode but the sprite is still my cube, it doesnt happen if i enter a mini portal while in a normal ball

**Comment by ImXyper** [comment]
![image](https://github.com/dankmeme01/globed2/assets/54502653/54b6f198-9254-4e6f-84cf-99e9ef8c9cb0)

**Comment by muhdqausar01** [comment]
GDPS swing copter mode be like..

**Comment by dankmeme01** [comment]
fixed in next update (https://github.com/dankmeme01/globed2/commit/5d5976753e9d12aca2dff78f5ea6ae6a4858c290)
