### ISSUE TITLE
Can't load more than 30 people

### ISSUE THREAD

**Issue by Hanuko33** [dankmeme01/globed2#94]
When I join any level with more than 30 people, it just doesn't display them

**Comment by dankmeme01** [comment]
have you tried doing the Packet Limit test in settings? after doing it try reconnecting to the server and see if the issue is resolved.

**Comment by Hanuko33** [comment]
Yes, I tried. Sadly didn't help...

**Comment by Hanuko33** [comment]
It's fixed now
