### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by Waffle234** [dankmeme01/globed2#96]
![image_2024-02-22_010856251](https://github.com/dankmeme01/globed2/assets/160823361/2bd1e685-47bf-4628-b076-4c92a2dfabcc)

can someone tell me how to fix this

**Comment by Ruslansimba** [comment]
Perhaps the servers have been disabled, try to look in the central-server and game-server console

**Comment by CallocGD** [comment]
I'm having the same issue connecting to the main server can someone explain this bug?  No matter how hard I try. I keep trying and trying to hit the login button, I even updated to the latest version, but I still get that same issue.
![image](https://github.com/dankmeme01/globed2/assets/140273795/c210a0b2-f0e3-4b14-b830-f62d34de5cdd)

**Comment by agamergamegd** [comment]
im also having the same problem :/

**Comment by CallocGD** [comment]
Now I got Error code: 521

**Comment by CallocGD** [comment]
![image](https://github.com/dankmeme01/globed2/assets/140273795/632efe28-e3b2-448b-b6fa-93a7d651e54a)

**Comment by CallocGD** [comment]
Whelp I looked it up it means Webserver is down

**Comment by dankmeme01** [comment]
indeed the servers were down
