### ISSUE TITLE
error code 521

### ISSUE THREAD

**Issue by Ducbao2013** [dankmeme01/globed2#97]
![screenshot_1708598132](https://github.com/dankmeme01/globed2/assets/109129688/7aceb2b0-23a4-4f9b-9212-9e9c3218cad6)
How to fix this?

**Comment by Ducbao2013** [comment]
![screenshot_1708598583](https://github.com/dankmeme01/globed2/assets/109129688/45cb2353-eed3-4bd8-8802-d086146175a5)
...

**Comment by dankmeme01** [comment]
update the mod to the latest version

**Comment by Ducbao2013** [comment]
> update the mod to the latest version

thanks
