### ISSUE TITLE
tcp connection timed out, failed to connect after 5 seconds

### ISSUE THREAD

**Issue by Se1d228** [dankmeme01/globed2#98]
Globed error
Failed to connect: tcp connection timed out, failed to connect after 5 seconds
[OK]
 
![image](https://github.com/dankmeme01/globed2/assets/114381573/c2de2940-f77b-4a0c-b855-82665325ce4d)

**Comment by Se1d228** [comment]
![image](https://github.com/dankmeme01/globed2/assets/114381573/5f698636-e488-43bc-9017-dadd27149f8f)

**Comment by DELTAFYREX** [comment]
i have same issue

**Comment by dankmeme01** [comment]
try to update to v1.2.1 and see if it's fixed

**Comment by dankmeme01** [comment]
closing since there was no response
