### ISSUE TITLE
Bridged server dont work for other users code 400

### ISSUE THREAD

**Issue by mihkostas** [dankmeme01/globed2#99]
![image](https://github.com/dankmeme01/globed2/assets/47123339/602afff5-b179-4adf-9585-30af3e78b6d0)
I test it with wireshark and my server response to users with (http 400 Bad Request) and they cant connect,
even tho i can connect to it normally.

**Comment by dankmeme01** [comment]
are they able to open the server URL in a browser? does that also not load or does it work fine?

**Comment by mihkostas** [comment]
> are they able to open the server URL in a browser? does that also not load or does it work fine?

It seems it works now, after some reinstallations my friend did to his globed2 mod ( for the record it did work only in the brower for him at the time i open the issue).
